version: "3.2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_network

  php:
    build: ./dockerfile.dev.yml
    volumes:
      - ./code:/code
    networks:
      - php_network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb2
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - php_network

networks:
  php_network:
